article/urls.py
from django.urls import path

from article.apps import ArticleConfig
from article.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    published

app_name = ArticleConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    path('published/<int:pk>', published, name='published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('article/', include('article.urls', namespace='article')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, get_new_password, VerifyCodeView
from django.contrib.auth.views import LoginView, LogoutView
app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    path('get_new_password/', get_new_password, name='get_new_password'),
]

article/models.py
from django.db import models
NULLABLE = {"blank": True, "null": True}

class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name="заголовок")
    slug = models.CharField(max_length=150, **NULLABLE, verbose_name="slug")
    body = models.TextField(max_length=150, **NULLABLE, verbose_name="содержимое")
    image = models.ImageField(upload_to="catalog/", **NULLABLE, verbose_name="превью")
    date_creation = models.DateTimeField(**NULLABLE, verbose_name="дата создания")
    sign_publication = models.CharField(max_length=150, verbose_name="признак публикации")
    number_views = models.IntegerField(default=0, verbose_name="количество просмотров")

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='положительно опубликованы')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.title} {self.slug}'

    class Meta:
        verbose_name = 'статья'  # Настройка для наименования одного объекта
        verbose_name_plural = 'статьи'  # Настройка для наименования набора объектов

article/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from article.models import Article


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'body',)
    success_url =reverse_lazy('article:list')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'body',)
    # success_url =reverse_lazy('article:list')


    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('article:view', args=[self.kwargs.get('pk')])


class  ArticleListView(ListView):
    model = Article

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset



class  ArticleDetailView(DetailView):
    model = Article


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('article:list')



def published(request, pk):
    article_item = get_object_or_404(Article, pk=pk)
    if article_item.is_published:
        article_item.is_published = False
    else:
        article_item.is_published = True
    article_item.save()
    return redirect(reverse('article:list'))

article/templates/article/article_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'article:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

article/templates/article/article_detail.html
{%  extends 'catalog/home.html'%}
{% load my_tag %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top"
                            src="{{ object.image|mediapath }}"
                             alt="Card image cap">
                    <h3 class="card-title">Пост "{{ object.title }}" ({{ object.slug }})</h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

article/templates/article/article_form.html
{% extends 'catalog/home.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

article/templates/article/article_list.html
{% extends 'catalog/home.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'article:create' %}">Добавить пост</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card md-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                    {{ object|title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'article:view' object.pk %}"
                    class="btn btn-sm btn-outline-secondary">Показать</a>
                    <a href="{% url 'article:edit' object.pk %}"
                        type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                    <a href="{% url 'article:delete' object.pk %}"
                        type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                </div>
                 {% if object.is_published %}
                    <a class="btn btn-warning" href="{% url 'article:published' object.pk %}">Снять с публикации</a>
                {% else %}
                    <a class="btn btn-success" href="{% url 'article:published' object.pk %}">Опубликовать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}