article/urls.py
from django.urls import path

from article.apps import ArticleConfig
from article.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    published

app_name = ArticleConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    path('published/<int:pk>', published, name='published'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, index, CatalogListView, ProductCreateView, ProductListView, \
    ProductUpdateView, ProductDeleteView, ProductDetailView, published

app_name = CatalogConfig.name



urlpatterns = [
    path('contacts/', contacts),
    path('', index, name='index'),
    path('products/', ProductListView.as_view(), name='products'),
    path('catalog/<int:pk>/', CatalogListView.as_view(), name='inform'),
    path('<int:pk>/view_product/', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('create_product/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('<int:pk>/edit_product/', ProductUpdateView.as_view(), name='edit_product'),
    path('<int:pk>/product/', ProductDeleteView.as_view(), name='delete_product'),
    path('published/<int:pk>', published, name='published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('article/', include('article.urls', namespace='article')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, get_new_password, VerifyCodeView
from django.contrib.auth.views import LoginView, LogoutView
app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    path('get_new_password/', get_new_password, name='get_new_password'),
]

catalog/models.py
from django.db import models

# Create your models here.
NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="наименование")
    description = models.TextField(max_length=150, **NULLABLE, verbose_name="описание")
    created_at = models.CharField(**NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'категории'  # Настройка для наименования набора объектов


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name="наименование")
    description = models.TextField(max_length=150, **NULLABLE, verbose_name="описание")
    image = models.ImageField(upload_to="catalog/", **NULLABLE, verbose_name="изображение")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="категория")
    price = models.IntegerField(verbose_name="цена за штуку")
    date_creation = models.DateTimeField(**NULLABLE, verbose_name="дата создания")
    last_modified_date = models.DateTimeField(**NULLABLE, verbose_name="дата последнего изменения")

    is_published = models.BooleanField(default=True, verbose_name='положительно опубликованы')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.title} {self.description}'

    class Meta:
        verbose_name = 'продукт'  # Настройка для наименования одного объекта
        verbose_name_plural = 'продукты'  # Настройка для наименования набора объектов


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(default=1, verbose_name='Номер')
    name = models.CharField(max_length=100, default='Создана', verbose_name='Название')
    is_active = models.BooleanField(default=True, verbose_name='Активная')

    def __str__(self):
        return f'{self.name} {self.number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StileFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_title(self):
        cleaned_title = self.cleaned_data['title'].lower()
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in words:
            if word in cleaned_title:
                raise forms.ValidationError(f'В названии продукта не должно быть слова {word}')
        return cleaned_title

    def clean_description(self):
        cleaned_description = self.cleaned_data['description'].lower()
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in words:
            if word in cleaned_description:
                raise forms.ValidationError(f'В описании продукта не должно быть слова {word}')
        return cleaned_description



class VersionForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


# Create your views here.

def contacts(request):
    if request.method == 'POST':
        # в переменной request хранится информация о методе, который отправлял пользователь
        name = request.POST.get('name')
        telephone = request.POST.get('phone')
        message = request.POST.get('message')
        # а также передается информация, которую заполнил пользователь
        print(name, telephone, message)
    return render(request, 'catalog/contacts.html')


def index(request):
    context = {
        'object_list': Product.objects.all(),
        'title': f"Магазин продуктов"
    }
    return render(request, 'catalog/index.html', context)


# def products(request):
#     context = {
#         'object_list': Product.objects.all(),
#         'title': f"Магазин продуктов"
#     }
#     return render(request, 'catalog/category_list.html', context)





# def inform(request, pk):
#     products_item = Product.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(pk=pk),
#         'title': f"{products_item.name}"
#     }
#     return render(request, 'catalog/catalog.html', context)

class CatalogListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = f"{products_item.title}"
        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')



class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': "Каталог продуктов",
        'current_user': settings.AUTH_USER_MODEL,
    }



class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_formset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = version_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = version_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)



class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')





class ProductDetailView(DetailView):
    model = Product
    extra_context = {
        'title': "Карточка продукта",
    }


def published(request, pk):
    prod_item = get_object_or_404(Product, pk=pk)
    if prod_item.is_published:
        prod_item.is_published = False
    else:
        prod_item.is_published = True
    prod_item.save()
    return redirect(reverse('catalog:home'))

catalog/templates/catalog/catalog.html
{% extends 'catalog/home.html' %}
{% load my_tags %}

{% block content %}
<div class="row text-center">
    {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <img class="card-img-top"
                             src="{{ object.image|mediapath }}"
                             alt="Card image cap">
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ object.price}} руб.</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.category}}</li>
                            <li>{{ news_form.end_date|default_if_none:object.description }}</li>
                            <li>{{ news_form.end_date|default_if_none:object.image}}</li>
                            <li>{{ news_form.end_date|default_if_none:object.date_creation}}</li>
                            <li>{{ news_form.end_date|default_if_none:object.last_modified_date}}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    </div>
                </div>
            </div>
    {% endfor %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Вкусняшка
                    <small class="d-block mb-3 text-muted">&copy; 2024</small>
                </div>


</footer>
{% endblock %}

catalog/templates/catalog/categories.html
{% extends 'catalog/home.html' %}
{% load my_tags %}

{% block content %}
<div class="row text-center">
    {% for object in object_list %}
                {% include 'catalog/includs/inc_category.html' %}
    {% endfor %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Вкусняшка
                    <small class="d-block mb-3 text-muted">&copy; 2024</small>
                </div>


</footer>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}

{% block content %}
<div class="row text-center">
    {% for object in object_list %}
                {% include 'catalog/includs/inc_category.html' %}
    {% endfor %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Вкусняшка
                    <small class="d-block mb-3 text-muted">&copy; 2024</small>
                </div>


</footer>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <input type="submit" value="Отправить" />
                    </form>

                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Вкусняшка</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' %}">Товары</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'article:list' %}">Статьи</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Всегда свежие и вкусные</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/home.html' %}
{% load my_tags %}

{% block content %}
<div class="row text-center">
    {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <img class="card-img-top"
                             src="{{ object.image|mediapath }}"
                             alt="Card image cap">
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ object.price}} руб.</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.category}}</li>
                            <li>{{ news_form.end_date|default_if_none:object.description }}</li>
                            <li>{{ news_form.end_date|default_if_none:object.image}}</li>
                            <li>{{ news_form.end_date|default_if_none:object.date_creation}}</li>
                            <li>{{ news_form.end_date|default_if_none:object.last_modified_date}}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    </div>
                </div>
            </div>
    {% endfor %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    SkyStore
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>

</footer>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
 <form method="post" class="row">
     <div class="col-6">
         <div class="card">
             <div class="card-header">
                Удаление карточки
             </div>
             <div class="card-body">
                 {% csrf_token %}
                 <p>Подтвердите удаление карточки {{ object.name }}</p>
                 <button type="submit" class="btn btn-outline-danger">
                         Удалить
                 </button>
                 <a class="btn btn-outline-warning" href="{% url 'catalog:products' %}">Отмена</a>
             </div>
         </div>
     </div>
 </form>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}

{% block content %}
{% load my_tags %}
<div class="card" style="width: 20rem;">
    <img src="{{ object.image|mediapath }}" class="card-img-top" alt="Изображение отсутствует">
    <div class="card-body">
        <h5 class="card-title">{{ object.name }}, {{ object.price | floatformat:2 }} руб</h5>
        <p class="card-text">{{ object.description|slice:100 }}.</p>
        <p class="card-text"> Актуальная версия {{ object.active_version }}.</p>
<!--        <span class="text-muted">{{ object.owner|default:"-" }}</span><br>-->
        <a href="#" class="btn btn-primary">Купить</a>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html'  %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6 mb-5">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                     Редактировать карточку продукта
                 {% else %}
                     Добавить карточку продукта
                 {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
<div class="col-6">
          <div class="card">
                <div class="card-header">
                    <h5 class="card-title">
                        Версии продукта
                    </h5>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}


{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.name }}</p>
            <p class="card-text"> Актуальная версия {{ object.active_version }}.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:view_product' object.pk %}" class="btn btn-secondary">Показать</a>
                    <a href="{% url 'catalog:edit_product' object.pk %}" class="btn btn-link">Изменить</a>
                    <a href="{% url 'catalog:delete_product' object.pk%}" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
        <div class="card-footer">
            {% if perms.catalog.set_is_published %}
                {% if object.is_published %}
                    <a class="btn btn-outline-warning" href="{% url 'catalog:published' object.pk %}">Снять с публикации</a>
                {% else %}
                    <a class="btn btn-outline-success" href="{% url 'catalog:published' object.pk %}">Опубликовать</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}